### ISSUE TITLE
Please add .idea folder to repo

### ISSUE THREAD

**Issue by TWiStErRob** [JakeWharton/dagger-reflect#10]
for shared code style and inspection profile, see for example:
https://github.com/TWiStErRob/android-realistic/blob/90864275cefb018bd158a09368d577785a235422/.gitignore#L30-L36

and potentially do a full format on the project

**Comment by TWiStErRob** [comment]
ah!

> It uses https://github.com/square/java-code-styles right now (as do all my projects). I've been debating about using google-java-format but it does some nasty things to builders. I should probably relent, though. -- [JakeWharton](https://github.com/JakeWharton/dagger-reflect/pull/59#discussion_r258207307)

**Comment by JakeWharton** [comment]
#124!

**Comment by TWiStErRob** [comment]
Nice, thanks!

(Square's annotation style makes so much more sense, but I guess this is why it's anti-bs, no choices)

**Comment by JakeWharton** [comment]
That style is the same as Google's, it's just that google-java-format
doesn't respect it for whatever reason.
