### ISSUE TITLE
Using component as a dependency

### ISSUE THREAD

**Issue by Laimiux** [JakeWharton/dagger-reflect#136]
I'm curious if there are plans to add support for the following use case. I'm using the root component as an injected parameter in the same graph. For example: 
```kotlin
@Module
object AppModule {
    @Provides fun provideFeatureViewModel(component: AppComponent) 
        = Feature.create(component) 
}
```

A bit more complete example:
```kotlin
object Feature {
    interface Dependencies {
        fun foo(): Foo
    }

    @Component(dependencies = [Dependencies::class])
    interface FeatureComponent {
        fun featureViewModel(): FeatureViewModel
    }

    fun create(dependencies: Dependencies): FeatureViewModel {
        return TODO()
    }
}

@Component(modules = [AppModule::class])
interface AppComponent : Feature.Dependencies {

}

@Module
object AppModule {
    @Provides fun provideFeatureViewModel(component: AppComponent) 
        = Feature.create(component) 
}
```

**Comment by JakeWharton** [comment]
So you're saying that Dagger exposes a binding for the component instance inside that component automatically? And presumably this works for subcomponents as well?

**Comment by Laimiux** [comment]
Correct, though I'm not sure if parent component binding is available within the subcomponent graph.

**Comment by JakeWharton** [comment]
Should be easy to test for!

**Comment by Laimiux** [comment]
Added a test for this functionality #138. I've looked a little bit into the code base to add this functionality. Given the sort of cyclical nature of this, it's not completely obvious how to best add it. Maybe you already have ideas?

**Comment by JakeWharton** [comment]
My current thinking here is that during scope construction we can put a semi-mutable binding into the graph for the (sub)component type and then sneak the instance into the binding after the scope and (sub)component has been created.

**Comment by Laimiux** [comment]
Sounds reasonable, will take a look at implementing it.
