### ISSUE TITLE
Desugared static methods on module interfaces not visible via reflection

### ISSUE THREAD

**Issue by emartynov** [JakeWharton/dagger-reflect#176]
I'm trying to use dagger reflect and app is failing on startup. I have a situation like:

```

@Module
ModuleA {
 @Provides dependencyA() : A
}

@Module(includes={ModuleA.class})
ModuleB {
 @Provides dependencyB(): B
}

class B @Inject constructor (a: A)

```

I'm looking to the source https://github.com/JakeWharton/dagger-reflect/blob/master/reflect/src/main/java/dagger/reflect/ReflectiveModuleParser.java and looks like includes annotation is not used.

**Comment by JakeWharton** [comment]
Includes are handled here:
https://github.com/JakeWharton/dagger-reflect/blob/master/reflect/src/main/java/dagger/reflect/ComponentScopeBuilder.java#L47

What's the full stack trace of the failure?

**Comment by emartynov** [comment]
I was thinking that dependencies from includes are also available in this module.

```
java.lang.IllegalStateException: Missing binding for android.content.ClipboardManager
     * Requested: company.android.debug.config.DebugConfigContract$Presenter
         from @Binds[company.android.debug.config.di.DebugConfigModule.presenter(…)]
     * Requested: company.android.debug.config.DebugConfigPresenter
         from @Inject[company.android.debug.config.DebugConfigPresenter.<init>(…)]
     * Requested: company.android.debug.config.logic.ProfileDataInteractor
         from @Inject[company.android.debug.config.logic.ProfileDataInteractor.<init>(…)]
     * Requested: android.content.ClipboardManager
         which was not found.
```

And we have:
```

@Module(includes = {AndroidApplicationModule.class})
abstract class DebugConfigModule
{
  @Binds
  abstract DebugConfigContract.Presenter presenter(DebugConfigPresenter presenter);
}
@Module
public interface AndroidApplicationModule
{
  @Provides
  static ClipboardManager provideClipboardManager(Context context) {
    return (ClipboardManager) context.getApplicationContext().getSystemService(Context.CLIPBOARD_SERVICE);
  }
}
```

**Comment by TWiStErRob** [comment]
@JakeWharton managed to reproduce: https://github.com/TWiStErRob/dagger-reflect/tree/issue176
It worked perfectly fine until I moved `DebugConfigModule` from an IntegrationTest component to be consumed via `ContributesAndroidInjector`.

**Comment by TWiStErRob** [comment]
```diff
-public interface AndroidApplicationModule
+public class AndroidApplicationModule
```
makes it work with `ContributesAndroidInjector` too

**Comment by TWiStErRob** [comment]
`dagger.reflect.ReflectiveModuleParser#parse(AndroidApplicationModule.class, null, ...)` fails to iterate `for (Method method :` because `AndroidApplicationModule.class.getDeclaredMethods()` returns a 0-length array, so does `getMethods()`.

When debugging on https://github.com/TWiStErRob/dagger-reflect/commit/207d1916324e2a4f2c7ca8cdcfe6a1e5cae81f8f the test running on local JVM correctly returns the static method.

**Comment by TWiStErRob** [comment]
This also makes it work (keeping `interface AndroidApplicationModule`):
```diff
-minSdkVersion 21
+minSdkVersion 24
```

**Comment by TWiStErRob** [comment]
This also makes it work (keeping `interface` and `minSdkVersion 21`):
```diff
-    classpath 'com.android.tools.build:gradle:3.4.1'
+    classpath 'com.android.tools.build:gradle:3.5.1' // or 3.5.0
```

**Comment by emartynov** [comment]
@TWiStErRob are you sure it is related to my original issue?

**Comment by TWiStErRob** [comment]
If you run the app from `:integration-tests:android` on the branch I linked above, you'll get a very similar stack trace. I realize now that `@ContributesAndroidInjector` is a red herring, the key is having a `static` method in an `interface` on Android with minSdk < 24 and AGP < 3.5.x. If you confirm that all of these are true for you, we'll know for sure.

**Comment by JakeWharton** [comment]
I'm tempted to do nothing here. We could encode the desugaring scheme and look up the companion class that's used to hold the static methods, but that's very said (and fragile).

**Comment by emartynov** [comment]
People, please :) My original issue was not about the static methods

**Comment by TWiStErRob** [comment]
@emartynov Can you get a breaking example in a fork branch like I did? The `includes` are implemented and tested, the only thing that reproduced your issue was static interface methods. Could this be a http://xyproblem.info?

**Comment by emartynov** [comment]
You're opening my eyes. I was sure it is `includes` related issue. Let me check if it is indeed the interface methods.

**Comment by emartynov** [comment]
Oke, just to keep you updated. It was indeed the static produce methods in the interface modules. We had a couple of such (around 6-9) and converting them to the Object allowed me to move further.

**Comment by emartynov** [comment]
Also interesting to explore minSDK 24 mentioned above.

**Comment by emartynov** [comment]
I'm closing it.

**Comment by catellie** [comment]
Not a wonderful solution, but this small patch to ReflectiveModuleParser will allow you to access the desugared methods:
```  
  /**
   * Wrapper for Reflection.getDistinctTypeHierarchy which also tries to find any
   * desugared class on interfaces as these static classes can be needed.
   * @param moduleClass the visible class
   * @return distinct type hierarchy for both visible and desugared classes
   */
  static Set<Class<?>> getDesugaredDistinctTypeHierarchy(Class<?> moduleClass) {
    Set<Class<?>> targets = Reflection.getDistinctTypeHierarchy(moduleClass);
    if (moduleClass.isInterface())
      try { // There may be a desugared dummy class
        ClassLoader loader = moduleClass.getClassLoader();
        String desugarClassName = moduleClass.getName() + "$-CC";
        Class<?> desugarClass = loader.loadClass(desugarClassName);
        targets.addAll(Reflection.getDistinctTypeHierarchy(desugarClass));
      } catch (ClassNotFoundException e) {
        // No sugar, no problem
      }
    return targets;
  }

  static void parse(Class<?> moduleClass, @Nullable Object instance, Scope.Builder scopeBuilder) {
    for (Class<?> target : getDesugaredDistinctTypeHierarchy(moduleClass)) {
```

**Comment by Javagic** [comment]
I have an issue like this. I'd like to hold @Binds and @Provides methods in one dagger module class. 
And this code works perfect in common dagger, but it fails for runtime reflection.

```
@Module
abstract class Module {
    @Binds
    abstract fun provideFoo(value: FooImpl): Foo

    companion object {
        @Provides
        fun provideClass() = Static.getClass
    }
}
```
   Will it be possible with dagger reflect?

**Comment by catellie** [comment]
@Javagic I never finished my experiment with dagger reflect due to the generics issue, but you may get around the problem you see by annotating provideClass with `@JvmStatic` (possibly in combo with my snippet in my previous snippet).

Good luck!
