### ISSUE TITLE
MinSdkVersion 24?

### ISSUE THREAD

**Issue by bnvinay92** [JakeWharton/dagger-reflect#178]
Static interface methods are only supported starting with Android N (--min-api 24): dagger.reflect.JustInTimeLookup dagger.reflect.JustInTimeLookup$Factory.lambda$static$0(dagger.reflect.Key)

Are people declaring a different product flavor with minSdkVersion 24 to get this to work?

**Comment by kokeroulis** [comment]
Probably related to this one https://github.com/JakeWharton/dagger-reflect/issues/176#issuecomment-540851401

**Comment by bnvinay92** [comment]
Looks like I forgot to declare that the sample app consuming my library (which uses dagger) should use Java 8.
