### ISSUE TITLE
Default method implementation isn't handled in component interface

### ISSUE THREAD

**Issue by Jacks0N23** [JakeWharton/dagger-reflect#219]
I have AppComponent interface with some default methods inside, because I need to pass deps inside another component:
```
interface AppComponent {
    default ProfileComponent createProfileComponent() {
        return DaggerProfileComponent.builder()
                .profileDependencies(this)
                .profileDocumentDependencies(this)
                .build();
    }
}
```

## Current behavior
throws exception `java.lang.IllegalArgumentException: No provider available for`

## Expected behavior
dagger-reflect checks that it's default method and invoke it implementation

**Comment by TWiStErRob** [comment]
@Jacks0N23 I think you should keep the issue open in case there'll be more work on this project.
